name: Docker Image Downloader
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Save Image
        run: |
          docker pull node:20-bookworm-slim
          docker save node:20-bookworm-slim > node_image.tar
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-node-image
          path: node_image.tar
