name: Docker Image Downloader
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Save Python
        run: |
          docker pull python:3.11-slim-bookworm
          docker save python:3.11-slim-bookworm > python_3.11_slim.tar
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-image-package
          path: python_3.11_slim.tar
